[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$rLVWinHOmTNmzPl/zxkjpA$Q6ivzXPmcQ9eEKnjVTPpXhL9zJpSncDWDsTfk5XSTf16Jfa7yaPwxVHtGlP19AALtDxACo./AbIo4caHvihQ6Q

